### ISSUE TITLE
log self during method calls

### ISSUE THREAD

**Issue by tapple** [mzipay/Autologging#12]
I was trying to use this to trace a recursion error in an accidentally recursive data structure, but I noticed it only logged the non-self parameters of a method, whereas I was primarily interested in what self happened to be at each call

**Comment by mzipay** [comment]
Hi @tapple,
Yes, this is by design.  The self argument is really an "implicit" argument for bound functions (not unlike Java's "this"), but Python's function call semantics just happen to require that it be explicit.  Autologging is not likely to change in this regard.
When you say "what self happened to be at each call" I don't quite see your meaning.  If the method was accidentally recursive, the identity of self would not change during the recursion.
Do you mean that you were trying to identify which particular object's (out of many objects) method was recursing? In that case, something as simple as `self.__log.debug("I am %r", self)` or `self.__log.debug("I am %r @%x", self.__class__, id(self))` at the beginning of the function would give you the information you're after.
