### ISSUE TITLE
addition of 'timing' information on RETURN log when using @traced

### ISSUE THREAD

**Issue by tschockaert** [mzipay/Autologging#14]
Hi,

Would it be possible to add the following enhancement:
- on the RETURN log line when @traced is used, adding (optionally) timing information that shows how long the CALL took

I know that it is possible to compare CALL and RETURN timestamps and infer the time it took from that, but that seems hack-ish. I think that it would be useful to have either a @timed decorator that enhances @traced, or have an option like @traced(timed=True).

Kind regards,

Thomas Schockaert

**Comment by mzipay** [comment]
Hi Thomas,
Thanks for the suggestion.
Function elapsed time is definitely useful information, but I hesitate on adding this to Autologging for a couple reasons.
1. Function timing (correctly) requires the use of a monotonic clock. While Python's `time` module has included a `monotonic()` function since 3.3, it is not widely available outside of CPython (and Autologging is committed to supporting other platforms).  This doesn't mean it's impossible - just that it would require significantly more effort than you might realize to support it in Autologging, and that effort relative to its priority means it would probably not get done any time soon.
2. As useful as this information is, it is generally **not** implemented by a general tracing mechanism (which is what Autologging is) but rather by a dedicated tracer for timing information or by a log scraper.  For a dedicated timer, see https://docs.python.org/3.8/library/trace.html.  There are several log scrapers for Python, but I'm not familiar enough with any of them to provide recommendations.

I will consider adding a dedicated `@timed` tracing decorator in a future release (though I would likely not "bake in" that functionality to the core `@traced` decorator).
